[run]
init_cmds = [
	["go", "build", "-o", "goflappy", "main.go"],
	["./goflappy"]
]									# Commands run in start
watch_all = true					# Watch all sub-directories
watch_dirs = [
    "$WORKDIR/game",
    "$WORKDIR/res",
]						            # Directories to watch
watch_exts = [".go"]				# Extensions to watch
ignore = [
    ".git",
    ".idea",
    "node_modules"
] 	                                # Directories to exclude from watching
ignore_files = [
    ".+_test.go"
]					                # Regexps for ignoring specific notifies
build_delay = 1500					# Minimal interval to Trigger build event
interrupt_timout = 1				# Time to wait until force kill
graceful_kill = true				# Wait for exit and before directly kill
cmds = [
    ["go", "build", "-o", "goflappy", "main.go"],
	["./goflappy"]
]									# Commands to run